import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignInButton, SignUpButton } from "@clerk/nextjs";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";
import Sidebar from "@/Components/Sidebar";
import { Toaster } from "react-hot-toast";
import { currentUser } from "@clerk/nextjs/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  const user = await currentUser()
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className="min-h-screen">
            <div className="sticky-top">
            <Navbar />
            </div>
            {!user ? (
              <div>
                <div className="max-w-md mx-auto mt-10 p-6 border border-gray-200 rounded-lg shadow-md bg-white">
                  <div className="mb-4">
                    <h2 className="text-center text-xl font-semibold">Welcome Back!</h2>
                  </div>
                  <div>
                    <p className="text-center text-gray-500 mb-4">
                      Login to access your profile and connect with others.
                    </p>
                    <SignInButton mode="modal">
                      <button
                        className="w-full px-4 py-2 border border-gray-300 rounded-md text-gray-700 hover:bg-gray-50 transition"
                        type="button"
                      >
                        Login
                      </button>
                    </SignInButton>
                    <SignUpButton mode="modal">
                      <button
                        className="w-full mt-2 px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition"
                        type="button"
                      >
                        Sign Up
                      </button>
                    </SignUpButton>
                  </div>
                </div>
              </div>
            ) : <main className="py-5">
              <div className="max-w-7xl mx-auto px-4">
                <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
                  <aside className="hidden lg:block lg:col-span-3">
                    <div className="max-h-[calc(100vh-5rem)] overflow-y-auto">
                      <Sidebar />
                    </div>
                  </aside>
                  <div className="lg:col-span-9">
                    {children}
                  </div>
                </div>
              </div>
            </main> }
           

            {/* <Footer /> */}
          </div>
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
